service: go-image-compressor

provider:
  name: aws
  runtime: go1.x
  stage: poc
  region: sa-east-1
  memorySize: 256
  timeout: 5
  logRetentionInDays: 1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "*"

functions:
  handler:
    memorySize: 512
    handler: bin/handler
    events:
      - http:
          path: /
          method: GET
          cors: true
